### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by llrs** [llrs/BOE_historico#5]
With https://github.com/marketplace/actions/github-push

and with the schedule [from cransays](https://github.com/lockedata/cransays/blob/master/.github/workflows/cron.yml):

```

on:
  schedule:
    - cron:  '0 40 7 * * '

name: install BOE
use: Rscript -e "remotes::install.packages("rOpenSpain/BOE")
name: Run job
use: Rscript last
```
